# Generated by Django 4.2 on 2026-02-17 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField(db_index=True, verbose_name='شناسه کاربر')),
                ('template', models.CharField(choices=[('match_found', 'مچ جدید'), ('mawkab_approved', 'تایید موکب'), ('mawkab_rejected', 'رد موکب'), ('report_suspended', 'معلق شدن گزارش')], db_index=True, max_length=100, verbose_name='قالب پیام')),
                ('channel', models.CharField(choices=[('messenger', 'پیام\u200cرسان')], max_length=20, verbose_name='کانال')),
                ('payload', models.JSONField(default=dict, help_text='پارامترهای template مثل match_id, report_id', verbose_name='پارامترها')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال شده'), ('failed', 'ناموفق'), ('blocked', 'بلاک شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('platform_message_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='شناسه پیام در پلتفرم')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('deep_link', models.CharField(blank=True, help_text='مثلاً peyda://match/{matchId}', max_length=500, null=True, verbose_name='Deep Link')),
                ('metadata', models.JSONField(default=dict, verbose_name='متادیتا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'نوتیفیکیشن',
                'verbose_name_plural': 'نوتیفیکیشن\u200cها',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user_id', 'created_at'], name='notificatio_user_id_c62b26_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['template', 'status'], name='notificatio_templat_609034_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
    ]
