# Generated by Django 4.2 on 2026-02-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='شماره تماس')),
                ('role', models.CharField(choices=[('user', 'کاربر عادی'), ('mawkab_owner', 'صاحب موکب'), ('admin', 'ادمین')], default='user', max_length=20, verbose_name='نقش')),
                ('mawkab_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='اگر کاربر صاحب موکب است', null=True, verbose_name='شناسه موکب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_banned', models.BooleanField(default=False, verbose_name='مسدود')),
                ('ban_reason', models.TextField(blank=True, null=True, verbose_name='دلیل مسدودیت')),
                ('daily_report_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد گزارش امروز')),
                ('daily_report_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شمارش گزارش روزانه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_user_phone_9474e8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_activity_at'], name='users_user_last_ac_ed8f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['mawkab_id'], name='users_user_mawkab__07d12a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
    ]
