# Generated by Django 4.2 on 2026-02-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mawkab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام موکب')),
                ('owner_name', models.CharField(max_length=200, verbose_name='نام صاحب موکب')),
                ('owner_phone', models.CharField(max_length=20, verbose_name='شماره تماس صاحب موکب')),
                ('owner_user_id', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='شناسه کاربر صاحب')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='طول جغرافیایی')),
                ('address', models.TextField(blank=True, verbose_name='آدرس متنی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد')),
                ('total_reports', models.PositiveIntegerField(default=0, verbose_name='تعداد کل گزارش\u200cها')),
                ('resolved_reports', models.PositiveIntegerField(default=0, verbose_name='تعداد گزارش\u200cهای حل شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
            ],
            options={
                'verbose_name': 'موکب',
                'verbose_name_plural': 'موکب\u200cها',
            },
        ),
        migrations.AddIndex(
            model_name='mawkab',
            index=models.Index(fields=['status'], name='mawkab_mawk_status_60de43_idx'),
        ),
        migrations.AddIndex(
            model_name='mawkab',
            index=models.Index(fields=['owner_user_id'], name='mawkab_mawk_owner_u_89334b_idx'),
        ),
        migrations.AddIndex(
            model_name='mawkab',
            index=models.Index(fields=['latitude', 'longitude'], name='mawkab_mawk_latitud_3f613f_idx'),
        ),
    ]
