# Generated by Django 4.2 on 2026-02-17 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='شماره تلفن')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل ادمین',
                'verbose_name_plural': 'پروفایل\u200cهای ادمین',
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('approve', 'تأیید'), ('reject', 'رد')], max_length=10, verbose_name='عملیات')),
                ('model_name', models.CharField(max_length=50, verbose_name='نام مدل')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسه شیء')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت',
                'verbose_name_plural': 'لاگ فعالیت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('manage_reports', 'مدیریت گزارش\u200cها'), ('manage_mawkab', 'مدیریت موکب\u200cها'), ('manage_users', 'مدیریت کاربران'), ('view_stats', 'مشاهده آمار'), ('suspend_report', 'تعلیق گزارش'), ('verify_mawkab', 'تایید موکب')], max_length=20, verbose_name='دسترسی')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='اعطا شده توسط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی ادمین',
                'verbose_name_plural': 'دسترسی\u200cهای ادمین',
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
