# Generated by Django 4.2 on 2026-02-17 04:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.PositiveSmallIntegerField(verbose_name='امتیاز شباهت (۰-۱۰۰)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('rejected', 'رد شده')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('notified_report_id', models.UUIDField(blank=True, null=True, verbose_name='شناسه گزارشی که نوتیفیکیشن دریافت کرد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان رد')),
                ('rejected_by_user_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه کاربر رد\u200cکننده')),
            ],
            options={
                'verbose_name': 'تطبیق',
                'verbose_name_plural': 'تطبیق\u200cها',
                'ordering': ['-similarity_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('lost', 'گمشده'), ('found', 'پیداشده')], max_length=10, verbose_name='نوع گزارش')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('resolved', 'حل شده'), ('suspended', 'معلق')], default='active', max_length=15, verbose_name='وضعیت')),
                ('name', models.CharField(max_length=200, verbose_name='نام فرد')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سن')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, null=True, verbose_name='جنسیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image_urls', models.JSONField(default=list, help_text='لیست URL تصاویر (حداکثر ۵ عکس)', verbose_name='آدرس تصاویر')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='طول جغرافیایی')),
                ('address', models.TextField(blank=True, verbose_name='آدرس متنی')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('user_id', models.PositiveIntegerField(db_index=True, verbose_name='شناسه کاربر ثبت\u200cکننده')),
                ('mawkab_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='اگر توسط موکب ثبت شده باشد', null=True, verbose_name='شناسه موکب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان حل شدن')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان معلق شدن')),
                ('suspended_by_admin_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه ادمین معلق\u200cکننده')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user_id'], name='reports_rep_user_id_f032ac_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['mawkab_id'], name='reports_rep_mawkab__2ba5db_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['gender'], name='reports_rep_gender_eb7fef_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['latitude', 'longitude'], name='reports_rep_latitud_bfcbfa_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='reports_rep_status_22ec20_idx'),
        ),
        migrations.AddField(
            model_name='match',
            name='report_found',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_found', to='reports.report', verbose_name='گزارش پیداشده'),
        ),
        migrations.AddField(
            model_name='match',
            name='report_lost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_lost', to='reports.report', verbose_name='گزارش گمشده'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='reports_mat_status_3b0e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['similarity_score'], name='reports_mat_similar_171696_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['created_at'], name='reports_mat_created_653f57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('report_lost', 'report_found')},
        ),
    ]
