# Generated by Django 4.2 on 2026-02-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(db_index=True, unique=True)),
                ('user_id', models.PositiveIntegerField(db_index=True)),
                ('endpoint', models.CharField(max_length=200)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Idempotency Record',
                'verbose_name_plural': 'Idempotency Records',
                'db_table': 'api_idempotency_record',
            },
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['key', 'user_id'], name='api_idempot_key_f2ef62_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['created_at'], name='api_idempot_created_fb8bf6_idx'),
        ),
    ]
